name = "Flexible-SEO-Hugo"
license = "MIT"
licenselink = "https://github.com/pjbakker/flexible-seo-hugo/blob/master/LICENSE"
description = "A theme with flexible home, nav, header and footer styles and staying SEO friendly"
homepage = "http://github.com/pjbakker/flexible-seo-hugo/"
tags = [ "bootstrap", "customizable", "responsive" ]
features = [ "breadcrumbs", "structured-data" ]
min_version = "0.63.0"

[author]
  name = "Paul Bakker"
  homepage = "https://brain-dump.space"
