baseurl = "https://example.com"
languageCode = "en-us"
title = "Flexible SEO Hugo"
theme = ["flexible-seo-hugo"]
googleAnalytics = ""
enableRobotsTXT = true
disableHugoGeneratorInject = true
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[Params]
  description = "A flexible SEO friendly theme for Hugo"
  schemas = []
  page_schemas = []
  seo = []

[taxonomies]

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

